### PR TITLE
InMobi: Updating support for sites

### PR DESCRIPTION
**Pull request by cormorinth**
Adding site to static yaml, and exemplary tests

### CODE REVIEW

**Review by SyntaxNode — APPROVED** [review]

**Review by mansinahar — APPROVED** [review]

**Comment by mansinahar** [comment]
Can you please also open a doc PR to include `pbs_site_supported: true` in the table here: https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/inmobi.md as well?

**Comment by SyntaxNode** [comment]
Thank you @mansinahar. I didn't realize the docs include app and site support. @cormorinth We'll wait to merge this in until the docs PR is created.

**Comment by cormorinth** [comment]
I've done as asked, although I don't see reference of that string anywhere in the docs (https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html), or within code searches of the entire https://github.com/prebid/prebid.github.io repo.

**Comment by SyntaxNode** [comment]
> The mismatch between the yaml configuration and the docs is quite curious as pbs_app_supported seems to imply web as a given, but my (poorly informed) presumption is that it's a holdover from prebid originally being prebid.js.

Thank you. Indeed, that is curious. You very may well be correct. We'll have that discussion in the prebid.github.io PR. We're all good here.

**Pull request merged**
