### PR TITLE
GDPR: Don't Call Bidder If It Lacks Purpose 2 Legal Basis

### PR DESCRIPTION
**Pull request by bsardo**
**Refactor changes:**
- changed the name of the GDPR method `PersonalInfoAllowed` to `AuctionActivitiesAllowed` since that method now determines whether a bid request is allowed in addition to whether personal info is allowed.
- changed the name of `allowID` and `allowGeo` to `passID` and `passGeo` because they sound more like activities.
- removed obselete tests `TestAllowPersonalInfoTCF2PurposeOneTrue` and `TestAllowPersonalInfoTCF2PurposeOneFalse` in `impl_test.go` that correspond to obselete code deleted in #1839

**Logic changes:**
- added logic in `cleanOpenRTBRequests` that filters out any blocked requests just before returning
- created a new test for `cleanOpenRTBRequests` that specifically tests the bid request functionality and left the existing GDPR test for testing PI scrubbing.
- added logic in allowActivitiesTCF2 to determine whether to block the request
- added a new test for `allowActivitiesTCF2` that specifically tests the bid request functionality and left the existing test `TestAllowActivitiesTCF2` for testing PI.
- if GDPR applies and there is no consent string or there is an error parsing the consent string, the bid request is not allowed IAW spec requirement 17 in the Prebid Server section

### CODE REVIEW

**Comment by bsardo** [comment]
I did not add an E2E JSON framework test inside the exchange package to verify bid requests are blocked. It would require some changes to the test framework, particularly making the GDPR permissions mock configurable via new fields set in the JSON spec. I figured the coverage at the UT level was sufficient but I can add this if others feel it is necessary.

**Review by hhhjort — DISMISSED** [review]
LGTM. Nice, relatively simple change.

**Review by hhhjort — APPROVED** [review]

**Review by AlexBVolcy — DISMISSED** [review]
LGTM!

**Comment by bsardo** [comment]
Please hold off on merging. I'm going to push up a couple of changes shortly, one of which adds a metric for when a request is blocked by GDPR.

**Review by AlexBVolcy — APPROVED** [review]

**Pull request merged**
