### PR TITLE
New Adapter: Stailamedia

### PR DESCRIPTION
**Pull request by kleins**

### CODE REVIEW

**Comment by kleins** [comment]
Documentation: https://github.com/prebid/prebid.github.io/pull/4358

**Comment by kleins** [comment]
Hi @onkarvhanumante, 
do you have any news on this? 
Thanks a lot. 
Sascha

**Comment by SyntaxNode** [comment]
Hi @kleins. I am verifying with Xandr that they support adding an Stailamedia alias.

**Comment by kleins** [comment]
@SyntaxNode, thank you for your reply. My customer Stailamedia would not implement an Alias Adapter, because the adapter should get special functionality over the time. So we will happy, when the adapter could merged. Thx

**Comment by kleins** [comment]
Hi @SyntaxNode, as I said, the adapter is a copy of Xandr. This was talked to xandr. Xandr has some limits in their adapter, which will rebuild by the Stailamedia Adapter in the future. So this pull request is urgent required for Stailamedia to start their process. Stailamedia now also talking to Xandr again for pushing this pull request. ;-) Thx

**Pull request closed without merging**
