### PR TITLE
Set storedRequestTimeoutMillis as cutomizable config variable

### PR DESCRIPTION
**Pull request by amaurybrisou**
Set storedRequestTimeoutMillis as global config variable, allowing http fetchers timeout customization through stored_requests.http.fetcher_timeout config.
https://github.com/prebid/prebid-server/issues/1527

### CODE REVIEW

**Review by SyntaxNode — COMMENTED** [review]
Thank you for the contribution. I suggested a different config location. Do you think it's possible to add a unit test for the endpoints?

**Comment by amaurybrisou** [comment]
> Do you think it's possible to add a unit test for the endpoints?

is it related to this PR ?

**Comment by amaurybrisou** [comment]
> Thank you for the contribution. I suggested a different config location. Do you think it's possible to add a unit test for the endpoints?

Sure I can do that but where ? on the ```stored_requests/fetcher_test.go``` level or individual endpoints ? 

```stored_requests/fetcher_test.go``` doesn't look a good place because it's mainly for cache tests and cache will obviously break the test. 
```stored_requests/multifetcher_test.go``` ?

Thanks

**Comment by SyntaxNode** [comment]
> Sure I can do that but where ? on the stored_requests/fetcher_test.go level or individual endpoints ?

At the individual endpoint level. The change you're making doesn't change the fetcher code, it's the call site in the endpoints when calling into the fetcher code.

Don't worry if the code is too hard to reach with a unit test. I just think it's worth a check. The change is straight forward enough that major rework of the endpoint isn't necessary to add a test.

**Comment by SyntaxNode** [comment]
@amaurybrisou Friendly reminder about this PR.

**Comment by amaurybrisou** [comment]
Yep I'm sorry, I don't have the time to code all the tests and it has quite a lot. I will asap hopefully

**Comment by SyntaxNode** [comment]
> Yep I'm sorry, I don't have the time to code all the tests and it has quite a lot. I will asap hopefully

No worries. Just want to keep it on your radar. I didn't mean to overwhelm you with the ask for tests. If it's simple to do, then great. If it will be too much work to find a way a test, then I'll consider that beyond the scope of this PR as there are no existing tests.

**Comment by holms** [comment]
@[amaurybrisou](https://github.com/amaurybrisou) maybe you could please take a look at this again, or I can submit new PR? I mean having 50ms for external endpoint of stored requests, which can be like any IAAS or database-as-a-service out is a bit strange don't you think?

**Comment by SyntaxNode** [comment]
@holms This PR was automatically closed by our stalebot when the original author stopped responding. We have no issue with adding this feature if you'd like to take over development and open a new PR.

**Pull request closed without merging**
