### PR TITLE
Beachfront: Fix for bid floor issue#1787

### PR DESCRIPTION
**Pull request by muncha**

### CODE REVIEW

**Comment by muncha** [comment]
@SyntaxNode - can that failing test please be run again? The same command validates locally, and the error on that run occurs way after the bidders have all passed. Seems kind of random. Solar flares, maybe?

**Comment by SyntaxNode** [comment]
> @SyntaxNode - can that failing test please be run again?

Sure. It's rerunning now. Agreed that test failure looks odd.

**Comment by SyntaxNode** [comment]
The merge validation is failing. This usually points to a merge conflict of some kind. Can you please merge in the master branch? The failure is on a new test that was added yesterday.

**Review by bsardo — APPROVED** [review]
LGTM

**Review by AlexBVolcy — APPROVED** [review]
Looks good!

**Pull request merged**
