### PR TITLE
New Adapter: InteractiveOffers

### PR DESCRIPTION
**Pull request by IOTiagoFaria**
md file pr : https://github.com/prebid/prebid.github.io/pull/2879/

the adapters name is a bit longer then the existing ones, my IDE corrected the gaps so that they line up, if that's an issue I can always revert it and make a new commit for it.

### CODE REVIEW

**Comment by IOTiagoFaria** [comment]
Hi @bsardo and @SyntaxNode , to make sure that my fork has the last version, I've "re-forked" it from master.
I'll ask you to ignore this PR as a new one is being prepared, I've followed all the steps under the documentation and I still have 0% coverage of statements.
is there something that I should be aware of besides whats in the documentation?

**Comment by SyntaxNode** [comment]
> I'll ask you to ignore this PR as a new one is being prepared.

Sure. Just let us know when you're for a review. In the future, you may consider [updating your fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) instead of creating a new one.

> is there something that I should be aware of besides whats in the documentation?

Looks like you missed a step. The tests do not automatically run. You need a little bit of code to make that happen. Looks like you skipped the [Adapter Code Tests](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#adapter-code-tests) step.

**Comment by IOTiagoFaria** [comment]
@SyntaxNode many thanks for your help, I did tried to update my fork but I had no success as there were at least one new adapter that I was missing, next time I'll spend more time for it.

I do have a new PR with coverage of >90% 
https://github.com/prebid/prebid-server/pull/1819

**Comment by SyntaxNode** [comment]
> I do have a new PR

Excellent. I'll close this PR in favor of the other one.

**Pull request closed without merging**
