### PR TITLE
Modularity: Raw bidder response stage implementation

### PR DESCRIPTION
**Pull request by legendko**

### CODE REVIEW

**Comment by legendko** [comment]
Same here as in https://github.com/prebid/prebid-server/pull/2498

**Comment by bsardo** [comment]
@legendko I just pulled this PR down locally and resolved the error verifying it with `./validate.sh`. Somehow you ended up with two copies of `TestExtraBidWithMultiCurrencies` in `exchange/bidder_test.go` and they appear to be same except one copy is missing the empty hook executor as a parameter in a function call.

**Comment by legendko** [comment]
> `TestExtraBidWithMultiCurrencies`

I think I got it. Github was showing that I still have merge conflicts even after I updated the branch with master and I had to solve the issues on github itself. And that new commit created this duplicate issue. Solved now

**Review by hhhjort — DISMISSED** [review]
LGTM

**Review by bsardo — DISMISSED** [review]

**Review by bsardo — APPROVED** [review]

**Review by hhhjort — APPROVED** [review]
LGTM

**Pull request merged**
