### PR TITLE
Appnexus: Increase Code Coverage

### PR DESCRIPTION
**Pull request by Sonali-More-Xandr**
This PR adds test cases to cover all the possible code paths in the appnexus adapter code.

### CODE REVIEW

**Review by gargcreation1992 — COMMENTED** [review]
LGTM! Just curious, what is the diff in code coverage %age?

**Comment by Sonali-More-Xandr** [comment]
> LGTM! Just curious, what is the diff in code coverage %age?

Now the coverage is ~90%

**Comment by Sonali-More-Xandr** [comment]
> > > LGTM! Just curious, what is the diff in code coverage %age?
> > 
> > 
> > Now the coverage is ~90%
> 
> Could we aim for more if possible?

I haven't covered marshal unmarshal errors here

**Review by onkarvhanumante — APPROVED** [review]

**Comment by onkarvhanumante** [comment]
> > > > LGTM! Just curious, what is the diff in code coverage %age?
> > > 
> > > 
> > > Now the coverage is ~90%
> > 
> > 
> > Could we aim for more if possible?
> 
> I haven't covered marshal unmarshal errors here

okay to skip marshal unmarshal error paths

**Review by mansinahar — APPROVED** [review]

**Pull request merged**
