### PR TITLE
Add redirect sync to richaudienceAdapter

### PR DESCRIPTION
**Pull request by richaudience**

### CODE REVIEW

**Comment by VeronikaSolovei9** [comment]
Final URL I tested it with is https://sync.richaudience.com/f7872c90c5d3791e2b51f7edce1a0a5d/?p=pbs&consentString=&r=https%3A%2F%2Fprebid.adnxs.com%2Fpbs%2Fv1%2Fsetuid%3Fbidder%3Drichaudience%26gdpr%3D%26gdpr_consent%3D%26f%3Di%26uid%3D%5BPDID%5D
It returns too many redirects and doesn't redirect back to Prebid setuid url. 
Unless I missed something.

**Comment by richaudience** [comment]
Hi
We have already fixed it, we have applied a change internally. You can check this?
Cheers

**Comment by mansinahar** [comment]
@richaudience Thanks for fixing it. I tested the URL and I can now see a redirect with a UUID to prebid's setuid endpoint

**Review by mansinahar — APPROVED** [review]

**Review by VeronikaSolovei9 — APPROVED** [review]
Thank you for fixing it!

**Pull request merged**
