### PR TITLE
Marsmedia adapter - param zoneId can get string and int

### PR DESCRIPTION
**Pull request by vladi-mmg**

### CODE REVIEW

**Review by mansinahar — APPROVED** [review]
LGTM! Can you please update the documentation as well: https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/marsmedia.md

**Comment by VeronikaSolovei9** [comment]
It doesn't work with int, there is error message ` "message": "ext.bidder.zoneId not provided"` and no http requests to adapter. This happens due to imp ext definition where ZoneId is string. If it's int - it cannot unmarshal it and zone id is empty.
```
type ExtImpMarsmedia struct {
	ZoneID string `json:"zoneId"`
}
```

**Comment by vladi-mmg** [comment]
> It doesn't work with int, there is error message ` "message": "ext.bidder.zoneId not provided"` and no http requests are sent to adapter. This happens due to imp ext definition where ZoneId is a string. If it's int - it cannot unmarshal zoneid to int and zone id is empty.
> 
> ```
> type ExtImpMarsmedia struct {
> 	ZoneID string `json:"zoneId"`
> }
> ```
> 
> Update: to achieve desired result modify it to
> 
> ```
> package openrtb_ext
> 
> import "encoding/json"
> 
> // ExtImpMarsmedia defines the contract for bidrequest.imp[i].ext.marsmedia
> type ExtImpMarsmedia struct {
> 	ZoneID json.Number `json:"zoneId"`
> }
> ```
> 
> and use it as string: L86 `uri := a.URI + "&zone=" + marsmediaExt.ZoneID.String()` For working example refer to `openrtb_ext/imp_adf.go` and it's usage in code.

Thanks. I changed.

**Comment by mansinahar** [comment]
@vladi-mmg Thanks for updating the type of the field. Can you please add a JSON test for this as well?

**Review by VeronikaSolovei9 — DISMISSED** [review]

**Comment by VeronikaSolovei9** [comment]
Oh right, please add json test for this. Other than that LGTM.

**Comment by vladi-mmg** [comment]
> @vladi-mmg Thanks for updating the type of the field. Can you please add a JSON test for this as well?

I add new JSON test,  Did you mean that?

**Comment by mansinahar** [comment]
@vladi-mmg Yup! You, got it right. Thanks for updating. This is LGTM now but still waiting on the docs update for this here: https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/marsmedia.md. Can you please put up a PR to update that too? Once that PR is up, we can approve and merge this one.

**Comment by vladi-mmg** [comment]
@mansinahar As you know we used to have separate docs for Prebid Server and Prebid JS in the past.

The change to int in the Prebid server doc is the best practice for us, the reason why we've added the "string" is for supporting the already integrated clients of ours.
We have no interest of supporting "string" in the prebid JS doc as well.

**Review by mansinahar — APPROVED** [review]

**Review by VeronikaSolovei9 — APPROVED** [review]

**Pull request merged**
