### PR TITLE
Added Admixer adapter

### PR DESCRIPTION
**Pull request by DmitryStashkevich**
Admixer adapter for Prebid Server.
Test parameters:
[{"bidder":"admixer","bid_id":"random-id-from-pbjs-1","params":{"zoneOId":"5FE0AB26-1895-44C9-A970-76408D5F002D"}} ]

### CODE REVIEW

**Comment by dbemiller** [comment]
Hey @DmitryStashkevich,

A few weeks ago, Prebid Server transitioned towards OpenRTB support. We plan to update the existing adapters and switch Prebid.js to use the OpenRTB endpoint sometime in mid-January.

Unfortunately, that means that Prebid Server can't accept new adapters unless they support OpenRTB. We're updating the prebid.org docs right now, but I'm sorry we're a bit late on it.

Here are some new docs which describe how to add an OpenRTB bidder. There's also an open PR (#234) which, when merged, contains some code which should make tests easier to write.

If your adapter is urgent and needs to be live in prebid.js before mid-January, feel free to implement both Bidder and Adapter. This will make your adapter work immediately... but also make sure we can update the prebidServerAdapter in prebid.js to use openrtb in the near future.

And of course, if you run into any problems implementing OpenRTB, please log issues about them. Feedback from people who submit the first few adapters is extremely valuable.

Thanks for the submission!

**Comment by DmitryStashkevich** [comment]
Hello @dbemiller ,
Thank you for reply! 

We are very interested in implementation of OpenRTB adapter for Prebid Server.  We would follow the git and docs updates, and hope we'll be in time with implementation in mid-January. :)

Best regards, Dmitry

**Comment by dbemiller** [comment]
ok, thanks!

Do you want to leave this PR open until then, or can I close it?

**Comment by DmitryStashkevich** [comment]
Hello @dbemiller ,
Sorry for late response. Yes you can close it.

**Comment by dbemiller** [comment]
it's all good

**Pull request closed without merging**
