### PR TITLE
Centralized OpenRTB Bidder tests

### PR DESCRIPTION
**Pull request by dbemiller**
See issue #217 for the motivation behind this. The basic goals are:

1. Simplify OpenRTB Bidder test code.
2. Create some sample requests which show proper use of bidder params.

I replaced the Appnexus adapter's tests with JSON that gives similar code coverage, to show how adapter test code can be replaced by simpler JSON files.

### CODE REVIEW

**Comment by hhhjort** [comment]
I do like how, with the actual http calls having been pulled out of the bidder code itself, it is now easy to define mock responses from the bidders for the bidder code to process.

For requests that generate errors, should we verify we are reporting the correct error?

Would there be utility in handling a request type that looks valid server side, but will generate an error by the bidder? For example, requesting an ad for a placement that has been deactivated. PBS can't know that this is a bad placement, but Appnexus will return an error. Do we want to verify that the error propagates correctly?

As for possible non-ideal requests, will take a little thought as to how we test both success pieces and error pieces.

**Comment by dbemiller** [comment]
yeah... that's why I deferred the non-ideal case. I'm sure I can come up with something... but it's not straightforward, and I was able to get similar code coverage with just these two.

I'll look into testing errors. That seems reasonable.

I'm not certain about the other case:

> Would there be utility in handling a request type that looks valid server side, but will generate an error by the bidder?

If a server returns a 4xx or 5xx, it's actually handled by `exchange/bidder` (it returns an error, and doesn't even call `MakeBids`)... so no need to test those at the `bidder/bidder` level.

Using your example, the only other behavior I can imagine is "if some invalid params get passed, the server returns a 2xx/no-bid."

But a no-bid response would go through `MakeBids` exactly like one which came from _valid_ request params... so that test case wouldn't actually improve your coverage in any way.

I'm thinking it's best to leave that case off for now. I got pretty solid test coverage on the Appnexus bidder code without it... so other people might find the same.

**Comment by dbemiller** [comment]
@mkendall07 You might be interested in this because the idea could port to javascript too.

I think we get _more_ value from it in PBS, because those race conditions are really brutal and a combined auction test will help prevent them... but it might be worth thinking about anyway.

**Comment by dbemiller** [comment]
All the feedback from @hhhjort (included some offline discussions) has been integrated, so this is ready for a thorough review now.

@sandraleon Since you're working on #210, you might want to take a look at this. These changes _should_ make it much easier to test any new adapter code.

**Comment by dbemiller** [comment]
ok.

I'm going to treat @hhhjort as a second reviewer, because he also looked it over before going on vacation. I've made all the changes we discussed, so he's probably ok with it.

**Pull request merged**
