### PR TITLE
Remove Adagio adapter

### PR DESCRIPTION
**Pull request by osazos**
This PR is just about to remove the Adagio adapter.

Thanks

### CODE REVIEW

**Comment by SyntaxNode** [comment]
The Adagio adapter was added to the Prebid Server project just 6 months ago. I'm sorry to see you leave. Could you please fill us in on your decision to remove your adapter?

**Comment by osazos** [comment]
Hi @SyntaxNode, 

We made this choice due the lack of consistency of Prebid Server integration by each owners. Actually we have to spent too much time to try to get a correct implementation of our adapter, which is even not always possible.

**Comment by mansinahar** [comment]
@osazos You will also have to add an entry for Adagio in this `disabledBidders` map here: https://github.com/prebid/prebid-server/blob/master/exchange/adapter_util.go#L81

**Comment by osazos** [comment]
Hi @mansinahar, it's done.

**Review by AlexBVolcy — DISMISSED** [review]

**Comment by mansinahar** [comment]
@osazos Thanks for adding that. Btw, I noticed that this line needs to be removed too: https://github.com/prebid/prebid-server/blob/master/config/config.go#L796. I think once you remove this, this PR should be good. Sorry, I missed that earlier.

**Comment by osazos** [comment]
hi @mansinahar, no prob, thanks for your review!.
It's done.

**Review by mansinahar — APPROVED** [review]

**Review by VeronikaSolovei9 — APPROVED** [review]
LGTM

**Pull request merged**
