### PR TITLE
Add bidder name key support

### PR DESCRIPTION
**Pull request by camrice**
This PR also contains a bugfix implemented by @VeronikaSolovei9

### CODE REVIEW

**Comment by SyntaxNode** [comment]
Can you please describe the bug this is fixing?

**Comment by VeronikaSolovei9** [comment]
@SyntaxNode @camrice we found a bug on bid deduplication logic. In case we find bids with same category or `pb_dur` we randomly deduplicate one of them. This can bid that was previously processed or bid on current iteration. In case we deduplicate bid from previous iteration and this is the only one bid in bidder - we need to remove the entire bidder from processing. Without this fix we removed "current iteration" bidder  instead of "previously processed" . bidder.

The fix is only  in one line: `seatBidsToRemove = append(seatBidsToRemove, dupe.bidderName)` in exchange.go. Unit test added.

**Comment by SyntaxNode** [comment]
If it's a bug though, why are you adding a new Ext input?

I'm concerned about changing the public contract without first discussing in a Prebid committee. Before we add this, I'd like for you to please create an issue in this project so at least the PBS committee can review it at the next meeting. I'm not a remember of the Video Committee, but hopefully you are and can discuss it there as well.

**Comment by camrice** [comment]
Understood! I can create the issue for adding the new field. We should probably split this PR up then right? The bugfix is certainly higher priority.

**Comment by SyntaxNode** [comment]
> Understood! I can create the issue for adding the new field. We should probably split this PR up then right? The bugfix is certainly higher priority.

Yes, please. If you split them up we can address the bug separately from the new feature.

**Comment by camrice** [comment]
Got it! I will close this one and have new PRs created.

**Pull request closed without merging**
