### PR TITLE
increasing the stale period to 2 months

### PR DESCRIPTION
**Pull request by bretg**
Followup to https://github.com/prebid/prebid-server/issues/1293

### CODE REVIEW

**Comment by SyntaxNode** [comment]
Do these changes apply to PRs as well?

**Comment by bretg** [comment]
I haven't seen a PR go stale. The yaml file comments indicate "issues"

**Comment by SyntaxNode** [comment]
> I haven't seen a PR go stale. 

I've seen it happen occasionally on adapter PRs. Usually the stale reminder on a PR raises a red flag and prompts the author to respond. In a few very rare cases, we let the stale PR close out after at least a month of inactivity.

I checked the docs. While the comment just says issues, it actually applies to both.

How about keeping the `daysUntilStale` at 7 and change the `daysUntilClose` to 30? That would work well for PRs. If you feel that too high for issues, can you define the issue config separately?

See the bottom of the usage example on the stalebot project page here: https://github.com/probot/stale

**Comment by SyntaxNode** [comment]
@bretg Friendly Ping

**Comment by SyntaxNode** [comment]
This has been reviewed and accepted verbally by the Prebid Server Committee.

**Pull request merged**
