### PR TITLE
Updating usersync url for Brightroll bidder

### PR DESCRIPTION
**Pull request by smithaammassamveettil**
Description:
Updating user sync url for brightroll bidder

### CODE REVIEW

**Comment by smithaammassamveettil** [comment]
Not sure why this build failure is happening. I tried the same build command(pasting below) and receiving same build error while running locally even on the Prebid master repo build as well. So I believe it is not due to my config change in the PR. Please let me know how to fix this?

```
./validate.sh --nofmt

ok  	github.com/prebid/prebid-server/endpoints/info	(cached)
# github.com/prebid/prebid-server/exchange
exchange/utils_test.go:104:7: cannot use 1 (type int) as type *int8 in field value
ok  	github.com/prebid/prebid-server/endpoints/openrtb2	(cached)
?   	github.com/prebid/prebid-server/errortypes	[no test files]
FAIL	github.com/prebid/prebid-server/exchange [build failed]
ok  	github.com/prebid/prebid-server/gdpr	(cached)
```

**Comment by mansinahar** [comment]
Hi @smithaammassamveettil! Yes, unfortunately on master one of the tests is failing right now. I have created #851 to fix that. Once that is merged, I'd request you to rebase and update this PR. Hopefully, it should all be good then.

**Comment by smithaammassamveettil** [comment]
@mansinahar Thanks Mansinahar. I can see your PR got merged now. So I just rebased this and it looks good. 

Waiting for review please. @hhhjort

**Comment by smithaammassamveettil** [comment]
Thanks @hhhjort for reviewing and approving. Can you please merge this PR? Thanks!

**Comment by smithaammassamveettil** [comment]
Thanks @mansinahar for approving and merging this PR. Can you please let me know when this changes will be live in prebid production?

**Comment by mansinahar** [comment]
Hi @smithaammassamveettil! I think @hhhjort will be a better person to answer that question for you.

**Comment by smithaammassamveettil** [comment]
@hhhjort   Can you please let me know when this PR changes will be live in prebid production?

**Comment by hhhjort** [comment]
Don't have an exact schedule, but I am hoping tomorrow or thursday,

**Comment by smithaammassamveettil** [comment]
Thanks @hhhjort!  Can you please update me(here) when it is done?

**Comment by hhhjort** [comment]
I was reminded we are in a change freeze now, so I won't be able to update the appnexus install until next week.

**Comment by smithaammassamveettil** [comment]
@hhhjort Do you have any update now on when this change planning to release this week?

**Comment by hhhjort** [comment]
tuesday or wednesday

**Comment by smithaammassamveettil** [comment]
@hhhjort Is this change released now?

**Comment by hhhjort** [comment]
Oh, sorry, yes it is. I thought I saw you had been informed, but I must have ben mistaken.

**Comment by smithaammassamveettil** [comment]
When this change released ? yesterday(tuesday) or today? One of our clients is doing testing, so need to know exactly when this change is released? Can still see our old usersync url(not the updated url in the PR) in their tests today.

**Comment by hhhjort** [comment]
Approximately 1 pm EST yesterday

**Comment by hhhjort** [comment]
The configuration lists `https://pr-bh.ybp.yahoo.com/sync/appnexusprebidserver/?gdpr={{.GDPR}}&euconsent={{.GDPRConsent}}&url=https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D{{.GDPR}}%26gdpr_consent%3D{{.GDPRConsent}}%26uid%3D%24%7BUID%7D` as the usersync URL for Brightroll. Our current setup does not allow for using `externalURL` as the URL in the usersync, so we have an explicit entry in our configs.

**Comment by smithaammassamveettil** [comment]
@hhhjort We have modified the user sync url for brightroll bidder as seen in this PR as https://pr-bh.ybp.yahoo.com/sync/appnexusprebidserver/?gdpr=0&euconsent=&url=https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24UID.
Note: There is no %7B and %7D wrapping the UID param.

I can see this PR change in prebid master repository as well - https://github.com/prebid/prebid-server/blob/master/config/config.go#L415

But during client testing, they are getting the url which you mentioned above in the comment. Not the one I mentioned here, which is the correct one. How to do that update on the URL then?

**Comment by hhhjort** [comment]
I am sorry, that is entirely on me. I will get the correct configuration pushed to production today. As I mentioned, our install of PBS is using a configuration with all the usersync URLs set explicitly rather than using the defaults in the code.

**Comment by smithaammassamveettil** [comment]
@hhhjort Got it. Please let me know when it is ready for testing.

**Comment by hhhjort** [comment]
Sorry, this change is out. Had a busy day yesterday, but did get it out yesterday

**Pull request merged**
