### PR TITLE
Added macro support for cache URL

### PR DESCRIPTION
**Pull request by cindyhere33**
1. Prebid cache URL now contains three parts: scheme, host and query.
2. Query has macro support. Query contains %PBS_CACHE_UUID% that would be resolved into the UUID returned by the cache. 
3. Added scheme validations: supports only http and https.
4. Resolved previous conflicts.

### CODE REVIEW

**Comment by dbemiller** [comment]
Don't mind the CI failures... they're failing due to https://github.com/xojoc/useragent/issues/18, and fixed in #181.

If possible, please feel free to review #181. I can't request it from you explicitly because you're not a project collaborator (and the only one who can add collaborators is on vacation this week)... but it will help make the CI work again.

**Comment by dbemiller** [comment]
Ok... I merged #181 and restarted the build... so *now* the CI failures are important :).

Looks like the code coverage is too low in `prebid-server/config.go`

**Comment by cindyhere33** [comment]
Thanks for the update! Hopefully the tests I've added align with the existing convention

**Comment by dbemiller** [comment]
yeah, tests look fine. Thanks!

**Pull request merged**
