### PR TITLE
removing IX's usersync default URL

### PR DESCRIPTION
**Pull request by ix-prebid-support**

### CODE REVIEW

**Comment by SyntaxNode** [comment]
Does IX still support user syncing, you just request hosts contact you directly for the url? .. or should the user syncer be removed for IX?

**Comment by ix-prebid-support** [comment]
@SyntaxNode We do support user syncing, we just don't have a good default value.

**Comment by SyntaxNode** [comment]
IMHO, you could likely simplify `adapters/ix/usersync_test.go` since there's no longer a need to validate the default url can be parsed. Something like:

```
func TestIxSyncer(t *testing.T) {
	syncURL := "http://anyHost/anyPath"
	syncURLTemplate := template.Must(
		template.New("sync-template").Parse(syncURL),
	)

	syncer := NewIxSyncer(syncURLTemplate)
	syncInfo, err := syncer.GetUsersyncInfo(privacy.Policies{})

	assert.NoError(t, err)
	assert.Equal(t, "http://anyHost/anyPath", syncInfo.URL)
	assert.Equal(t, "redirect", syncInfo.Type)
	assert.EqualValues(t, 10, syncer.GDPRVendorID())
	assert.Equal(t, false, syncInfo.SupportCORS)
}
```

**Comment by ix-prebid-support** [comment]
Thank you.

**Review by SyntaxNode — APPROVED** [review]

**Review by guscarreon — APPROVED** [review]
LGTM

**Comment by muuki88** [comment]
@ix-prebid-support this means that each hosting company of prebid server as to negotiate it's own sync endpoint with you?

**Pull request merged**
