### PR TITLE
Fix Unruly Bidder Parmaters

### PR DESCRIPTION
**Pull request by SyntaxNode**
JSON Schema ids are case sensitive and the required params aren't matching. This is a fix of the case for the required constraint.

### CODE REVIEW

**Review by guscarreon — COMMENTED** [review]
Looks great, just one minor comment. In order to make sure the validation always works from here on, it'd be nice to have validation in a `adapters/unruly/params_test.go` file. I just tested the following with your changes locally and it works:
```
package unruly

import (
	"encoding/json"
	"testing"

	"github.com/prebid/prebid-server/openrtb_ext"
)

func TestValidParams(t *testing.T) {
	validator, err := openrtb_ext.NewBidderParamsValidator("../../static/bidder-params")
	if err != nil {
		t.Fatalf("Failed to fetch the json-schemas. %v", err)
	}

	for _, validParam := range validParams {
		if err := validator.Validate(openrtb_ext.BidderUnruly, json.RawMessage(validParam)); err != nil {
			t.Errorf("Schema rejected Unruly params: %s", validParam)
		}
	}
}

func TestInvalidParams(t *testing.T) {
	validator, err := openrtb_ext.NewBidderParamsValidator("../../static/bidder-params")
	if err != nil {
		t.Fatalf("Failed to fetch the json-schemas. %v", err)
	}

	for _, invalidParam := range invalidParams {
		if err := validator.Validate(openrtb_ext.BidderUnruly, json.RawMessage(invalidParam)); err == nil {
			t.Errorf("Schema allowed unexpected params: %s", invalidParam)
		}
	}
}

var validParams = []string{
	`{"uuid": "123", "siteid":"abc"}`,
}

var invalidParams = []string{
	`{}`,
	`null`,
	`true`,
	`154`,
	`{"siteId": 123}`,
	`{"uuid": "123"}`,
	`{"siteid":"abc"}`,
	`{"invalid_param": "123"}`,
	`{"uuid": 123, "siteid":"abc"}`,
	`{"uuid": "123", "siteid":123}`,
	`{"UUID": "123", "SiteId":123}`,
}
adapters/unruly/params_test.go
```

**Comment by SyntaxNode** [comment]
Good idea @guscarreon. Added.

**Review by guscarreon — APPROVED** [review]
Looks great

**Review by bsardo — APPROVED** [review]

**Comment by SyntaxNode** [comment]
Unruly will be reviewing this PR soon. Do not commit until they have a chance to review.

**Comment by SyntaxNode** [comment]
We expect Unruly to review this PR the first week in January.

**Comment by SyntaxNode** [comment]
I sent a reminder email to Unruly.

**Comment by rhythmonebhaines** [comment]
I'm Brian Haines from Rhythmone/Unruly. This looks good. I don't have an approval button so consider it approved.

**Comment by SyntaxNode** [comment]
@rhythmonebhaines That works. Thank you for reviewing. I'll merge it in now.

**Pull request merged**
