### PR TITLE
Remove Config Backwards Compatibility: DB Connection Info

### PR DESCRIPTION
**Pull request by bsardo**
The upcoming 2.0 release will remove backwards compatibility for deprecated host and account configuration options. This PR removes support for the following host options:
`{stored_requests/stored_video_req/stored_responses}.postgres.`
- `connection.dbname`
- `connection.host`
- `.connection.port`
- `.connection.user`
- `.connection.password`
- `.connection.query_string`
- `.connection.tls.root_cert`
- `.connection.tls.client_cert`
- `.connection.tls.client_key`
- `.fetcher.query`
- `.fetcher.amp_query`
- `.initialize_caches.timeout_ms`
- `.initialize_caches.query`
- `.initialize_caches.amp_query`
- `.poll_for_updates.refresh_rate_seconds`
- `.poll_for_updates.timeout_ms`
- `.poll_for_updates.query`
- `.poll_for_updates.amp_query`

Instead, hosts should use `.database` instead of `.postgres` when setting these fields.
e.g. `{stored_requests/stored_video_req/stored_responses}.database.connection.dbname`.

It should also be noted that since we now need to use the generic `.database` in our path, we must also set the driver as such: `{stored_requests/stored_video_req/stored_responses}.database.connection.driver`.

### CODE REVIEW

**Review by VeronikaSolovei9 — APPROVED** [review]
Local testing looks good for Postgres and MySQL.

**Comment by hhhjort** [comment]
I notice that the defaults for *.database.* , the new configs, are being removed. Is this intended?

**Comment by bsardo** [comment]
@hhhjort do you mean the `BindEnv` statements? I removed those while adding defaults for `.database`. Defaults make sense now that the backwards compatibility logic is gone since we don't need to manipulate the viper fields before assigning them to the structs. Plus by declaring defaults we ensure they can still be bound to environment variables.

**Review by hhhjort — APPROVED** [review]
LGTM

**Comment by hhhjort** [comment]
Yes, you are write. I managed to confuse red and green. I guess in a "remove" PR I wasn't expecting to see large chunks of code added.

**Review by VeronikaSolovei9 — APPROVED** [review]

**Review by hhhjort — APPROVED** [review]

**Pull request merged**
