### PR TITLE
Smaato: Send imp.ext object entirely

### PR DESCRIPTION
**Pull request by Enigo**
This PR refactors the way how our adapter sends the `imp.ext` object to the ad server - now the entire object is sent and not only `skadn`

### CODE REVIEW

**Review by eros902002 — APPROVED** [review]
Looks good to me

**Comment by bsardo** [comment]
Hi @Enigo, can you please merge with master (no rebase) and resolve conflicts? Thanks!

**Comment by Enigo** [comment]
@bsardo 
done, please check

**Review by przemkaczmarek — DISMISSED** [review]

**Comment by Enigo** [comment]
@bsardo 
is it possible to get this PR approved and merged?

**Review by bsardo — APPROVED** [review]

**Review by przemkaczmarek — APPROVED** [review]

**Comment by Enigo** [comment]
@bsardo @przemkaczmarek 
can we merge it?

**Pull request merged**
