### PR TITLE
Vrtcal Markets, Inc Adapter Integration

### PR DESCRIPTION
**Pull request by vrtcal-dev**
Vrtcal Markets, Inc Adapter Integration

### CODE REVIEW

**Comment by vrtcal-dev** [comment]
Thanks hhhjort.  The change to Gopkg.lock took place by the 'dep ensure' process. We noticed that it had changed but didn't think it mattered, not being part of the core code. We'll be happy to replace with the one from the master if necessary for your approval. Please let us know if this step is necessary...Thanks again

**Comment by hhhjort** [comment]
Yes, please update your PR so that Gopkg.lock is not included in it.

**Comment by vrtcal-dev** [comment]
We've updated to have the matching version of Gopkg.lock as the original so that it not included as a changed file.

**Comment by hhhjort** [comment]
Seems merge conflicts are happening now. :(

**Comment by hhhjort** [comment]
Still seeing merge conflicts for some reason

**Comment by vrtcal-dev** [comment]
Ok, complete repush again....no conflicts now.

**Comment by vrtcal-dev** [comment]
The last time we were at this point, another adapter was added to the master making our code have conflicts with the master. Is it possible for us to get this merged before this happens again?...Thanks..

**Comment by mansinahar** [comment]
@vrtcal-dev @hhhjort I think we should update the Gopkg.lock file if it is updating any packages as part of doing a `dep ensure` because that means that there's an update to one of the dependencies that we're using and it's good to have updated dependencies unless the update is causing issues for us. In that case, we should fix the issue or pin that dependency to the specific version we want.

**Comment by vrtcal-dev** [comment]
We no longer have a variation on the Gopkg.lock file. You can proceed with our integration as this is no longer an issue for us...Our version matches the master.

**Comment by vrtcal-dev** [comment]
Thanks hhhjort. When can we expect our adapter to be commited to the master?

**Comment by hhhjort** [comment]
We prefer a second review before merging to master. I have flagged this review as urgent so we should hopefully not get another merge conflict from something else merging first again.

**Comment by vrtcal-dev** [comment]
Thanks all. Will we see it added to the master today?

**Pull request merged**
