### PR TITLE
Add docs build readme 

### PR DESCRIPTION
**Pull request by bsardo**

### CODE REVIEW

**Comment by bsardo** [comment]
@justadreamer

**Comment by bsardo** [comment]
@SyntaxNode any thoughts on where we should put this README? I was going to put it in a `build` directory but that is actually a build process artifact which is ignored in `gitignore`.

**Comment by hhhjort** [comment]
Just a note for linux, `apt-get` is for debian based distributions. Red Hat based ones would use `rpm`, unless that has changed. But I would think anyone who wants to build on a linux system would know what their package manager is.

**Review by hhhjort — APPROVED** [review]

**Comment by bsardo** [comment]
> Hat based ones would use `rpm`, unless that has

Gotcha I'll make that clear. I know @justadreamer tested on debian based distributions and he provided the linux instructions.

**Review by hhhjort — DISMISSED** [review]

**Review by hhhjort — APPROVED** [review]

**Review by justadreamer — APPROVED** [review]
LGTM

**Review by guscarreon — APPROVED** [review]
LGTM

**Pull request merged**
