### PR TITLE
shared http.client

### PR DESCRIPTION
**Pull request by abramovic**
- ``prebid.DefaultHTTPClient`` can be shared by all of the prebid packages
- https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

### CODE REVIEW

**Comment by Abramovic** [comment]
I wasn't sure if the ssl certificates were required with every request which is why there are two different http.Clients. 

Thoughts?

**Comment by bokelley** [comment]
Is there a downside to attaching the certs if it's an HTTP request? I would think the library would just ignore them if not needed.

I'm worried about connection pooling in the case where we use the same client for everything. The reason it was separate was b/c I was thinking each endpoint would get its own pool. I suppose that isn't useful for something like captcha where it's a very rare call.

**Comment by Abramovic** [comment]
I'm not sure what will happen if the ssl certs are included but will do some research. 

Since the pbc.Put call might be inside of concurrent goroutines it's probably safer to construct a new http client with each request.

**Comment by mkendall07** [comment]
closing as stale

**Pull request closed without merging**
