### PR TITLE
Revert "Remove Adapter: Define Media"

### PR DESCRIPTION
**Pull request by dennisjay**
Dear PBS-Team,
at first sorry for the late reaction from our side. There were a lot of holidays and we just didn't see your messages on github.

In our repo I've reverted the commit, changed the email and made the pull request. Hope that was correct and that you can add us again soon.

Thanks.

### CODE REVIEW

**Comment by SyntaxNode** [comment]
Sent an email to the updates address for verification.

**Comment by SyntaxNode** [comment]
Email verification complete. We're all good there.

**Review by hhhjort — APPROVED** [review]
LGTM

**Comment by SyntaxNode** [comment]
Email confirmation received. We're all good here.

**Review by SyntaxNode — APPROVED** [review]

**Pull request merged**
