### PR TITLE
enforce video.size_id for video imps in rubicon adapter

### PR DESCRIPTION
**Pull request by Aadeshp**
cc: @bretg 

Based on conversations with Michael Moschovas over at Rubicon, it seems like video.size_id needs to be defined in every video request sent to rubicon

### CODE REVIEW

**Comment by mansinahar** [comment]
@Aadeshp Can you please also update the existing tests to account for this change? It is leading to failed tests. Also, it'd be great if you have a chance and can add a new test case for this that asserts a bad input error when the video size is not specified.

**Comment by mansinahar** [comment]
@rpanchyk @bretg Can you guys please take a look at this PR and make sure this the expected behavior for the Rubicon adapter. Once you give a thumbs up, we can fix the failing test.

**Comment by bretg** [comment]
Sorry - I get a lot of Prebid email and this one fell between the cracks. Please assign things to me or slack me if you want to get my attention.

Anyhow, I don't know where this one's coming from or that this is the right solution. Will work the team internally to figure it out.

**Comment by bretg** [comment]
Ok, worked through this with Michael. I understand and approve this change. 

Really the problem is that Prebid Server doesn't properly support outstream -- but that's a story for another day.

**Comment by SyntaxNode** [comment]
> Please assign things to me or slack me if you want to get my attention.

Will do next time. Sorry about that.

> Ok, worked through this with Michael. I understand and approve this change.

Thank you.

> Really the problem is that Prebid Server doesn't properly support outstream -- but that's a story for another day.

Sounds like a good item for the next agenda. 👍

**Comment by bretg** [comment]
I've asked Ruslan to review, but do we really need this change now? My understanding is that it was for a transition period that may have come and gone. (?)

**Comment by Aadeshp** [comment]
@bretg from my discussions with Michael, it sounded like this is a requirement for all video impressions, didn't mention anything about a transition period

**Comment by bretg** [comment]
Very well. Approved.

**Comment by SyntaxNode** [comment]
The test in this PR still needs to be fixed.

**Pull request merged**
