### PR TITLE
Brightroll: Remove Bidder

### PR DESCRIPTION
**Pull request by radubarbos**
The old Yahoo DSP adapter (brightroll) is not used anymore, the publishers moved on to the yahoo adapter.

### CODE REVIEW

**Review by Sonali-More-Xandr — COMMENTED** [review]
Please add Brightroll bidder to disabledBidders in [adapter_utils.go](https://github.com/prebid/prebid-server/blob/master/exchange/adapter_util.go#L87)

**Comment by radubarbos** [comment]
I've addressed the review comment, thank you.

**Comment by gargcreation1992** [comment]
@radubarbos PR checks are failing. Please check.

**Review by gargcreation1992 — APPROVED** [review]

**Comment by Sonali-More-Xandr** [comment]
@radubarbos We have sent a verification mail to confirm deletion of this adapter from Prebid. Please reply to mail from prebid@microsoft.com with subject `Brightroll Adapter Removal from Prebid` to move forward with this PR.

**Comment by gargcreation1992** [comment]
> @radubarbos We have sent a verification mail to confirm deletion of this adapter from Prebid. Please reply to mail from [prebid@microsoft.com](mailto:prebid@microsoft.com) with subject `Brightroll Adapter Removal from Prebid` to move forward with this PR.

@radubarbos requesting to please reply to the email.

**Comment by radubarbos** [comment]
hi, let me ask who team gets the old dsp-supply-prebid@verizonmedia.com emails

**Comment by gargcreation1992** [comment]
> hi, let me ask what team gets the old [dsp-supply-prebid@verizonmedia.com](mailto:dsp-supply-prebid@verizonmedia.com) emails

Thank you for being patient on this one. We have checked internally and this PR should be good to go.

**Comment by radubarbos** [comment]
> > hi, let me ask what team gets the old [dsp-supply-prebid@verizonmedia.com](mailto:dsp-supply-prebid@verizonmedia.com) emails
> 
> Thank you for being patient on this one. We have checked internally and this PR should be good to go.

Some emails were passed around yahoo DSP teams, I'll provide a comment here when I got the confirmation that a reply was sent.

**Comment by Sonali-More-Xandr** [comment]
@radubarbos Please remove [dev-docs](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/brightroll.md) of this adapter

**Comment by radubarbos** [comment]
Updated the docs https://github.com/prebid/prebid.github.io/pull/4762

**Comment by Sonali-More-Xandr** [comment]
> Updated the docs [prebid/prebid.github.io#4762](https://github.com/prebid/prebid.github.io/pull/4762)
> 
> I'm still waiting for the email reply confirmation.

That's fine. We discussed internally and we should be good to merge this PR. Thank you for your contribution!

**Review by Sonali-More-Xandr — APPROVED** [review]

**Pull request merged**
