### PR TITLE
Nobid: Add iframe sync support

### PR DESCRIPTION
**Pull request by redaguermas**
Added support for iframe user sync.

### CODE REVIEW

**Comment by redaguermas** [comment]
Can you please take a look at this PR? The validation failed for a module that is not ours.

**Comment by redaguermas** [comment]
Hello @bsardo ,
What should I do to get this PR going?

**Comment by redaguermas** [comment]
@bsardo Can you please review this PR?

**Comment by redaguermas** [comment]
Can someone please review this PR?

**Comment by redaguermas** [comment]
Can some one please review this PR?

**Comment by bsardo** [comment]
Hi @redaguermas, sorry for the slow response. I and a lot of the team have been out of the office recently on vacation. We'll make this a priority this week.

**Comment by SyntaxNode** [comment]
Confirmed the new iframe user sync endpoint works. However, please be advised the user id in my test is 729 characters long. We expect the id to be a much smaller (uuid length) opaque identifier. Based on the length, it looks like this uid may be encoding data.

You run the risk of hosts disabling your cookie sync since it uses a lot of valuable cookie storage space. Consider changing to a smaller id.

**Review by SyntaxNode — APPROVED** [review]

**Comment by redaguermas** [comment]
Thank you @SyntaxNode . We are going to look into creating a shorter ID but it will take some time because of technical changes that need to take place in the backend. Can you please merge this PR and we will address the ID length in another ticket/PR. 
-Regards

**Comment by SyntaxNode** [comment]
> We are going to look into creating a shorter ID but it will take some time because of technical changes that need to take place in the backend. Can you please merge this PR and we will address the ID length in another ticket/PR.

Much appreciated. Thank you.

 I mentioned this wasn't a blocker and already approved the PR. It's waiting for a second reviewer to approve and then you're good.

**Review by bsardo — APPROVED** [review]

**Pull request merged**
