### PR TITLE
VIS.X: add video instream support

### PR DESCRIPTION
**Pull request by mk0x9**
Hi, we've added instream video support in our server adapter.

### CODE REVIEW

**Comment by mk0x9** [comment]
@guscarreon @AlexBVolcy our team has decided to leave early exit as is. Extra test cases has been added to cover error cases in `getMediaTypeForImp`.

**Review by guscarreon — APPROVED** [review]
LGTM. Thank you for addressing our feedback

**Review by guscarreon — COMMENTED** [review]
Just to double-check: with this pull request, are you trying to also support ad podding in your ad server?

**Review by AlexBVolcy — APPROVED** [review]
This LGTM as well! But I'm also curious about Gus' question regarding support for ad podding.

**Comment by mk0x9** [comment]
Nope, didn't plan to. Should we change anything to explicitly set that we don't support them?

**Pull request merged**
