### PR TITLE
Ix remove size param

### PR DESCRIPTION
**Pull request by ix-prebid-support**
Sorry for the delay on this!

### CODE REVIEW

**Comment by ix-prebid-support** [comment]
@mansinahar let me know if it's too late for this!

**Comment by hhhjort** [comment]
We are releasing the initial PR now ... this bit is just code cleanup, will get it into the next release of PBS. Thanks for the cleanup.

**Comment by ix-prebid-support** [comment]
Sounds good and thank-you so much both @hhhjort @mansinahar

**Comment by mansinahar** [comment]
@ix-prebid-support You'd probably just need to rebase though. Thanks again for the PR!

**Comment by Aadeshp** [comment]
we should also remove the "size" parameter from the IX schema https://github.com/prebid/prebid-server/blob/master/static/bidder-params/ix.json

**Comment by hhhjort** [comment]
Yes, would be good to drop it if size no longer serves a use.

**Comment by ix-prebid-support** [comment]
Appreciate the insights here, will incorporate feedback and resubmit this!

**Pull request closed without merging**
