### PR TITLE
[fix] broken Go 1.9 compatibility

### PR DESCRIPTION
**Pull request by benjaminch**
This CL addresses Go 1.9 compatibility issue.

Issue: #895

### CODE REVIEW

**Comment by mansinahar** [comment]
Thank you so much @benjaminch for the PR! LGTM. Just one additional thing though, If we want to support Go 1.9 then we should also add that version in `travis.yml` so that these kind of issues are caught early.

**Comment by benjaminch** [comment]
Thanks ! Will add the version to the Travis ;)

**Comment by benjaminch** [comment]
just updated @mansinahar thanks :)

**Comment by hhhjort** [comment]
Do we still have people using go 1.9 to compile PBS? It is two versions back, but if there is a use case for it I am ok with it.

**Comment by benjaminch** [comment]
Hey @hhhjort , according to #895 the documentation was stating 1.9, so I guess some people are still using it.
Maybe we can merge this one, update the doc with the latest version to use and then remove 1.9 from the CI?

**Comment by benjaminch** [comment]
And here's the ticket for following steps: #920 
:)

**Pull request merged**
