### PR TITLE
New Adapter: Roundhouseads

### PR DESCRIPTION
**Pull request by juliansalinas121**
### Summary
This PR introduces the RoundhouseAds bidder adapter for Prebid Server. It supports the following media types:
- Banner
- Video
- Native

### Endpoints
- OpenRTB Endpoint: http://pbsv4-env.eba-qx2kfrgj.us-east-1.elasticbeanstalk.com/openrtb2/auction

### GDPR and GPP Compliance
- GVL Vendor ID: Using 42 temporarily until registration with IAB.
- GPP Supported: Yes

### Test Status
- Unit tests: All tests passed.
- JSON tests: Exemplary and supplemental tests added.

### Maintainer
- Email: info@roundhouseads.com

### CODE REVIEW

**Comment by juliansalinas121** [comment]
Hi Prebid team, this PR adds the RoundhouseAds adapter. Please let me know if any further changes are needed. Thanks for reviewing!

**Comment by bsardo** [comment]
Hi @juliansalinas121, we recently released PBS 3.0, more specifically v3.1.0, which updates Prebid Server package import references throughout the project from `v2` to `v3`.
For example:
```
import (
    "github.com/prebid/prebid-server/v3/adapters"
)
```
As a result, please merge with master (no rebase) and then ensure all Prebid Server package import references in the files you’ve changed are `v3` such that the test suite passes so we can resume reviewing. Thanks!

**Comment by juliansalinas121** [comment]
@bsardo, Closing this PR in favor of PR #4037, which includes the requested v3 updates and a merge with master.

**Comment by juliansalinas121** [comment]
Hi @bsardo, I'm closing this PR in favor of PR #4037, which includes the requested v3 updates and a merge with master.

**Pull request closed without merging**
