### PR TITLE
Require Bid.CrID properties

### PR DESCRIPTION
**Pull request by dbemiller**
This PR includes a breaking change for Bidders.

This was originally added in #414, complained about in #427, and reverted in #432. It is scheduled to be merged sometime in early May, to allow Bidders time to make the necessary changes.

See the `docs/developers/add-new-bidder.md` file in the diff for a summary of the changes.

### CODE REVIEW

**Comment by dbemiller** [comment]
Welp... it's May! @BZSky one final warning that this will merge & release in the next week or so.

**Comment by BZSky** [comment]
@dbemiller @hhhjort Hey guys! We are getting our merge request ready today. Would be super nice if you manage to approve and merge these two together. I will link it here as soon as we push it.

**Comment by dbemiller** [comment]
yeah, no problem.

**Comment by BZSky** [comment]
Thanks! Here's our PR:
https://github.com/prebid/prebid-server/pull/493

**Pull request merged**
