### PR TITLE
HB-1915: Metrics refactored and made configurable

### PR DESCRIPTION
**Pull request by cindyhere33**
1. Refactored metrics into a separate package
2. Metrics made configurable-`metric_type` could be either `counter` or `meter`(default).  
    pbs.json would include: 

> "metrics": {
    "type": "graphite",
    "host": "xxxxxxxx.carbon.hostedgraphite.com:2003",
    "interval": 30,
    "prefix": "API_KEY.prebid-server.test",
    "metric_type": "counter"
  }

3. prebid-server takes an optional runtime parameter `flush`. If given, counters are cleared upon logging (if reporting to graphite). 

NOTE: Update glide.yaml dependencies including `package: github.com/rubicon-project/go-metrics-graphite` to avoid errors with graphite initialization.

### CODE REVIEW

**Comment by dbemiller** [comment]
Could you explain the motivation here? What advantages does a flushable Counter have that a Meter doesn't?

I actually [wrote similar interfaces](https://github.com/prebid/prebid-server/pull/83) a while ago to support Influx tags, and immediately [got asked to revert it](https://github.com/prebid/prebid-server/pull/87) because the maintenance cost would be very high.

Can you give me some more details about the types of problems you're having with Meters? I might be able to suggest some simpler workarounds.

**Comment by cindyhere33** [comment]
Requesting @bretg, @DucChau to comment on this

**Comment by bretg** [comment]
Here's a writeup explaining the rationale. It's possible that flushable counters are only needed for hostedgraphite.  (yes, I tried the nonNegativeDerivative() function)

If APN is getting quantitatively correct values out of Influx is willing to give me some pointers on how to replicate this behavior, we could reconsider this PR.

-----------

The requirement from the business team is that the metrics reporting needs to be quantitatively correct, not just directional. This means that if 100 requests come in over 1 minute, the metrics reporting shows 100. If 100 requests come from each of 3 machines, reporting should show 300. Turns out this seemingly simple requirement isn't supported by hostedgraphite with the "Meter" metric type. Meters are monotonically increasing, so the counts don't represent how many precise requests were served in the period. The suggested solution on the internet was to use the "nonNegativeDerivative" function, but this doesn't work in hostedgraphite when more than one host is submitting data.

The only way I was able to achieve the requirement was to change the metric type to Counter AND clear the counters after each flush. This approach is not only intuitive, but works well in hostedgraphite without using functions.

When I talked to Matt Jacobson @ AppNexus about this, he implied their metric use was directional and satisfactory. It doesn't appear they're trying to get precise numbers out of the metrics for publisher reporting like we are.

So while flushed Counters work, it leaves us with a fairly different code base – the open source Prebid Server uses Meters, while our fork uses Counters and a hacked go-graphite library that flushes the counters.

This ticket tracks the generalization of the code base to configurably support both Meters and Counters.

**Comment by dbemiller** [comment]
That's what I was afraid of. Unfortunately... I think you may be barking up the wrong tree here. Time Series DBs just aren't made for this sort of thing. Some examples:

-------------------------------------------

I took a look at your `go-metrics-graphite` library. Like all the other `go-metrics-exporter` ones, exports run in a separate goroutine. But since `metric.Count()` and `metric.Clear()` are not atomic, your counts will still be unreliable. Auctions will run concurrently, and any increments which occur between those two lines will be lost.

It'd take much more hacking to share a mutex between `go-metrics-graphite` and the `inc*()` functions in this PR. ...And once you managed it, you'd then have a global lock which would "freeze" running auctions whenever metrics needed to be exported--so PBS performance would be terrible on the metrics flush interval.

------------------------------------------

These counters are stored in-memory. Eventually, you'll need to release a new version of the code. That involves shutting down the existing processes and starting up new ones instead.

Now suppose your export interval is every 10 seconds, and the "shutdown" command lands on the 7th second. The log of transactions for those first 7 seconds will be lost.

------------------------------------

Your guess is correct: I haven't been asked to implement precise numbers yet.

It sounds a bit to me like what we really need is some sort of transaction logger. There are a bajillion ways to implement these, varying in price and infrastructure complexity... but the simplest would just be a SQL database where each row is an event. BigQuery also accepts [events in a stream](https://cloud.google.com/bigquery/quotas#streaminginserts), which could be used to get more reliable data.

Leaving this comment here for now so you can see where I'm coming from... I'll try to come up with some more concrete improvements tomorrow

**Comment by cindyhere33** [comment]
Shall open a new PR for transactional logging.

**Pull request closed without merging**
