### PR TITLE
MobileFuse Adapter: add support for native

### PR DESCRIPTION
**Pull request by erictmf**

### CODE REVIEW

**Comment by erictmf** [comment]
We (MobileFuse) are ready to start handling native requests. The changes in this commit are isolated to native.

**Comment by AlexBVolcy** [comment]
This looks good! My only thing is could you link a docs PR that updates your dev-doc to reflect you now supporting native? Then I'll approve.

**Comment by erictmf** [comment]
dev docs pull request: (https://github.com/prebid/prebid.github.io/pull/4299)

**Review by hhhjort — APPROVED** [review]
LGTM

**Review by AlexBVolcy — APPROVED** [review]
LGTM

**Pull request merged**
