### PR TITLE
Config change for brightroll usersync url

### PR DESCRIPTION
**Pull request by smithaammassamveettil**
Description:

Updating usersync url for brightroll adapter

### CODE REVIEW

**Comment by smithaammassamveettil** [comment]
@dbemiller , Is this changes deployed on Prebid server? We are still seeing the old usersync url calls receiving at our end.

**Comment by smithaammassamveettil** [comment]
@dbemiller We noticed lot of below calls still recieving on our bid server, though this merged PR is to change this URL to point to different server
 [07/Jan/2019:16:42:25 -0000] "GET http://127.0.0.1/sync/appnexuspbs?gdpr=0&euconsent=&url=https%3A%2F%2Fprebid.adnxs.com%2Fpbs%2Fv1%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24%7BUID%7D HTTP/1.1" 200 43 200 43 0 0 588 1381 936 128 0 http/2 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256

Is there any tests running on your production prebid server which does making this calls? I noticed, I have used the old bid server url on 2 other test files - config_test.go and usersync_test.go. Not sure whether this causing issue?Can you please let me know is this test configuration is making this user sync test calls from Prod Prebid server?

**Comment by dbemiller** [comment]
@smithaammassamveettil It's deployed on Appnexus' instances of Prebid Server. It's an open source project, though, so other companies are hosting their own instances.

The `_test.go` files should not be hitting that endpoint. The automated tests for this project don't depend on external servers at all.

**Comment by dbemiller** [comment]
I merged it. I'd be very surprised if it fixed your issue... but it also shouldn't cause any harm.

**Comment by smithaammassamveettil** [comment]
I am not sure whether it will fix the issue. Just trying to filter out the possibilities. Will monitor today 
 and need to  investigate further if it didn't. Do you have any other insights what causing this issue other than some other company instances running tests?

**Comment by dbemiller** [comment]
I do not. I'll let you know if I think of anything.

**Pull request merged**
