### PR TITLE
33Across: Enable Support for SRA requests

### PR DESCRIPTION
**Pull request by curlyblueeagle**
In this PR we introduce SRA and group together Ad Units that have the same parameters under the same Bid Request in order to minimize http calls to our end point.

### CODE REVIEW

**Review by AlexBVolcy — COMMENTED** [review]
The code to update to support SRA looks good, but I want to bring to your attention that TestJsonSamples is failing with a test case from this path, 33acrosstest/exemplary/multi-imp-banner.json. Could you address this fail case?

**Comment by curlyblueeagle** [comment]
> The code to update to support SRA looks good, but I want to bring to your attention that TestJsonSamples is failing with a test case from this path, 33acrosstest/exemplary/multi-imp-banner.json. Could you address this fail case?

@AlexBVolcy tests seem to be running fine on my local and in our org's pipeline. Also it looks like the order of http reqs made of the Ad Requests matters in tests, so multiple requests would result in `expectedRequest` to not always have the same order and therefore the tests to flake. Do you have any suggestions on how I can check for the presence of requests in an agnostic manner?

**Comment by AlexBVolcy** [comment]
@curlyblueeagle I'll have an answer for what to do about this tomorrow!

**Comment by AlexBVolcy** [comment]
So after some investigating, the reason for this test failure is on our end, due to a shortcoming around the JSON Test Framework. 

So while we work on updating this framework, we'll need you to remove the test that is failing from this PR. We'll verify locally that this test is working properly, and we can approve this PR. 

Once we update the test framework, you can then open a new PR to add this test back in. 

Let me know if you have any other questions regarding this!

**Comment by guscarreon** [comment]
@curlyblueeagle pull request #2087 is meant to correct the false negatives our testing framework throws under certain `MakeRequests()` outputs. As soon as this newly posted PR gets approved and merged, your changes will pass validation (tested your changes locally with the test framework fix). Will let you know as soon as your fix gets merged

**Comment by curlyblueeagle** [comment]
@AlexBVolcy @guscarreon sorry I just removed the test that triggered the fail. Should I be waiting for the testing framework PR to be merged instead?

**Comment by guscarreon** [comment]
> @AlexBVolcy @guscarreon sorry I just removed the test that triggered the fail. Should I be waiting for the testing framework PR to be merged instead?

No @curlyblueeagle, we'll add your test case to #2087 instead. Is that ok?

**Comment by guscarreon** [comment]
@curlyblueeagle We've added your test case to #2087, it currently fails because this PR has not been merged yet. @AlexBVolcy and @VeronikaSolovei9 will continue to review your PR.

**Review by AlexBVolcy — APPROVED** [review]

**Review by VeronikaSolovei9 — APPROVED** [review]

**Comment by mansinahar** [comment]
@curlyblueeagle Can you please review the test added to #2087 for 33across to test this behavior and make sure it looks good?

**Comment by curlyblueeagle** [comment]
@mansinahar reviewed and looks good

**Pull request merged**
