### PR TITLE
Updated PubMatic endpoint to use https

### PR DESCRIPTION
**Pull request by PubMatic-OpenWrap**

### CODE REVIEW

**Comment by SyntaxNode** [comment]
There is a test failure with `TestDefaults`. For some reason, it appears the pubmatic url is used as a test value. Can you please either update the test or if you like, switch it to using the appnexus adapter as a test value.

You may also want to update `pubmatic_test.go` with the https variant to reduce confusion, although it's not strictly necessary.

**Comment by PubMatic-OpenWrap** [comment]
Fixed failing tests and updated endpoint url at appropriate places.

**Comment by SyntaxNode** [comment]
Changes look good. Why does it include the MarsMedia adapter as well? Perhaps something wrong with merging in from master?

**Comment by SyntaxNode** [comment]
Just wanted to check in to see if you can rebase the PR to remove the MarsMedia bits.

**Comment by PubMatic-OpenWrap** [comment]
Update PR with pull from prebid_master. Please verify.

**Pull request merged**
