### PR TITLE
Fix triplelift User Sync

### PR DESCRIPTION
**Pull request by Kevin-P-Kerr**
this allows native user syncs to redirect as expected, and fixes some gdpr issues.

### CODE REVIEW

**Comment by mansinahar** [comment]
@Kevin-P-Kerr Looks like gofmt is not happy. Can you please check and update the PR:
```
gofmt needs to be run, 2 files have issues.  Below is a list of files to review:
adapters/cpmstar/params_test.go
privacy/enforcement_test.go
```

**Comment by Kevin-P-Kerr** [comment]
hey @SyntaxNode  and @mansinahar , the whitespace changes are the result of running go fmt via 
```
./validate.sh
```

do you have any insight into what's happening?

**Comment by Kevin-P-Kerr** [comment]
for example, if I revert the whitespace

```
[kkerr_local prebid-server]$ git revert ea217b6ad9a159157482939c55f2cf8de466900b
```
running validate again will reformat those files
```
[kkerr_local prebid-server]$ ./validate.sh
Running: gofmt -s -w adapters/cpmstar/params_test.go
Running: gofmt -s -w privacy/enforcement_test.go
```
and result in the same diff

**Comment by SyntaxNode** [comment]
That's strange. I pulled down the branch and ran `./validate.sh` locally and it fixed the whitespace. I'm running Go 1.13.5. Maybe you have an older version or conflicting environmental options? I can commit a fix if you'd like.

**Comment by Kevin-P-Kerr** [comment]
hmmm, yeah it's strange 

```
[kkerr_local prebid-server]$ go version
go version go1.12.6 darwin/amd64
```

Not that far behind.  I'll just revert the ws change

**Pull request merged**
