### PR TITLE
Madvertise adapter: update email

### PR DESCRIPTION
**Pull request by jbartek25**
Fixing https://github.com/prebid/prebid-server/issues/2626

### CODE REVIEW

**Comment by Sonali-More-Xandr** [comment]
@jbartek25 We have sent a verification email to hb@azerion.com. Please reply to that email to complete the verification process.

**Comment by jbartek25** [comment]
@Sonali-More-Xandr replied

**Comment by Sonali-More-Xandr** [comment]
> @Sonali-More-Xandr replied

Thank you! Can you please also confirm that this is a group email address and not an individual email address?

**Comment by jbartek25** [comment]
Yes, this is a group email. FYI the same address is also used for Improve Digital adapter as they are both maintained/owned by Azerion.

**Review by onkarvhanumante — APPROVED** [review]

**Review by Sonali-More-Xandr — APPROVED** [review]

**Pull request merged**
