### PR TITLE
Kidoz: Update JSON Schema Reference To Type String

### PR DESCRIPTION
**Pull request by agilfix**
Remove definitions object from schema and define types and other parameters directly in properties objects to ensure compatibility with more downstream systems that use this schema.

### CODE REVIEW

**Comment by SyntaxNode** [comment]
We'll assign PBS reviewers once you have approval from Kidoz.

**Comment by SyntaxNode** [comment]
Kidoz approved via email.

**Review by SyntaxNode — APPROVED** [review]

**Review by guscarreon — APPROVED** [review]
LGTM

**Review by hhhjort — APPROVED** [review]
LGTM

**Pull request merged**
