### PR TITLE
Modularity: Bidder request stage implementation

### PR DESCRIPTION
**Pull request by legendko**

### CODE REVIEW

**Comment by legendko** [comment]
Not sure how to solve the issue `Validate Merge / validate-merge (pull_request)`. The branches `raw-auction-stage` and `master` are already merged into current branch without existing conflicts.

**Comment by SyntaxNode** [comment]
I'll try the age old IT of advice of "turning it off, an on again". Let's see if this works.

**Comment by SyntaxNode** [comment]
Closing and reopening this PR caused the tests to rerun. There are legit errors:

```
Error: exchange/bidder_test.go:2851:6: TestExtraBidWithMultiCurrencies redeclared in this block
Error: 	exchange/bidder_test.go:2[72](https://github.com/prebid/prebid-server/actions/runs/3742519679/jobs/6353563751#step:4:73)7:6: other declaration of TestExtraBidWithMultiCurrencies
Error: exchange/bidder_test.go:2957:3: not enough arguments in call to bidder.requestBid
```

Looks like a merge conflict or an error with a merge.

**Review by hhhjort — APPROVED** [review]
LGTM

**Review by VeronikaSolovei9 — APPROVED** [review]

**Pull request merged**
