### PR TITLE
Adapter for Somo Audience Bidder

### PR DESCRIPTION
**Pull request by bryandelong**
Official Somoaudience Adapter

### CODE REVIEW

**Comment by bryandelong** [comment]
Thanks.  I will follow this up with those GDPR changes soon.

**Comment by dbemiller** [comment]
@bryandelong we'll wait to merge until those GDPR changes are in.

The race condition tests that @hhhjort mentioned are pretty important too, although I don't think they're a dealbreaker. They just reduce the chance that we'll have to un-merge your adapter once we run load traffic through it.

**Comment by bryandelong** [comment]
GDPR has been implemented and the race conditions are also there.

**Comment by cirla** [comment]
It looks like some of @dbemiller's commits got pulled into this branch (e.g. the `go-gdpr` 0.6.0 uprev is already in master) -- would you be able to rebase on `master` for ease of reviewing?

**Comment by bryandelong** [comment]
Rebased.  Sorry about that.  Thought I did that already.

**Comment by dbemiller** [comment]
I made some conflicts by merging #520 on Friday... but they were simple, and I was hoping to release today... so I just fixed them here.

**Comment by dbemiller** [comment]
@bryandelong Is somoaudience on the GDPR [global vendor list](https://vendorlist.consensu.org/vendorlist.json)? I see:

```
{"id":341,"name":"Somo Audience Corp","policyUrl":"https://somoaudience.com/legal/","purposeIds":[1,2],"legIntPurposeIds":[3],"featureIds":[1,2,3]}
``` 

If so, you might want to add that to your `syncer.gdprVendorID`. Otherwise PBS won't sync with you in GDPR-affected regions.

**Comment by bryandelong** [comment]
Wasn't aware it went through so soon.  Updating and sending a new pr

**Pull request merged**
