### PR TITLE
rubicon adapter: Added bunch of new sizes

### PR DESCRIPTION
**Pull request by hdeodhar**
5: '120x90',
7: '125x125',
8: '120x600',
9: '160x600',
10: '300x600',
13: '200x200',
14: '250x250',
15: '300x250',
16: '336x280',
17: '240x400',
19: '300x100',
31: '980x120',
32: '250x360',
33: '180x500',
35: '980x150',
37: '468x400',
38: '930x180',
39: '750x100',
40: '750x200',
41: '750x300',
42: '2x4',
43: '320x50',
44: '300x50',
48: '300x300',
53: '1024x768',
54: '300x1050',
55: '970x90',
57: '970x250',
58: '1000x90',
59: '320x80',
60: '320x150',
61: '1000x1000',
64: '580x500',
65: '640x480',
66: '930x600',
67: '320x480',
68: '1800x1000',
72: '320x320',
73: '320x160',
78: '980x240',
79: '980x300',
80: '980x400',
83: '480x300',
85: '300x120',
90: '548x150',
94: '970x310',
95: '970x100',
96: '970x210',
101: '480x320',
102: '768x1024',
103: '480x280',
105: '250x800',
108: '320x240',
113: '1000x300',
117: '320x100',
125: '800x250',
126: '200x600',
144: '980x600',
145: '980x150',
152: '1000x250',
156: '640x320',
159: '320x250',
179: '250x600',
195: '600x300',
198: '640x360',
199: '640x200',
213: '1030x590',
214: '980x360',
221: '1x1',
229: '320x180',
230: '2000x1400',
232: '580x400',
234: '6x6',
251: '2x2',
256: '480x820',
257: '400x600',
258: '500x200',
259: '998x200',
264: '970x1000',
265: '1920x1080',
274: '1800x200',
278: '320x500',
282: '320x400',
288: '640x380'

### CODE REVIEW

**Review by bretg — APPROVED** [review]
The rubicon exchange apparently still needs this size mapping to happen here. I approve the addition of these sizes. Not sure if the final comma in the list will cause problems.

**Review by SyntaxNode — CHANGES_REQUESTED** [review]
~~@bretg commented before that the Rubicon/Magnite adapter in PBS no longer needs a list of sizes updated.~~
I see Bret's comment. Alrighty then. 👍

**Comment by bretg** [comment]
@SyntaxNode - will the comma after the 288 at the end of list be a problem here?

```
	{w: 320, h: 400}:   282,
	{w: 640, h: 380}:   288,
}
```

**Comment by hhhjort** [comment]
> @SyntaxNode - will the comma after the 288 at the end of list be a problem here?
> 
> ```
> 	{w: 320, h: 400}:   282,
> 	{w: 640, h: 380}:   288,
> }
> ```

Final comma is a go requirement, so it is needed, not a problem.

**Review by SyntaxNode — APPROVED** [review]

**Pull request merged**
